// <auto-generated />
namespace mavroudis_orestis_assignment_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202012191506033_initial_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
